apiVersion: v1
kind: Secret
metadata:
  name: techbleat-secret
  namespace: techbleat
type: Opaque
data:
  # echo -n "bankpass" | base64
  POSTGRES_PASSWORD: YmFua3Bhc3M=
  SPRING_DATASOURCE_PASSWORD: YmFua3Bhc3M=
  # echo -n "postgresql://bankuser:bankpass@postgres:5432/bankingdb" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL2Jhbmt1c2VyOmJhbmtwYXNzQHBvc3RncmVzOjU0MzIvYmFua2luZ2Ri
